/**
 * GENERATED by scripts/gen-icon-shims.mjs from scripts/icons.map.json — edit
 * the map, not this file.
 *
 * The app's icons are Tabler (outline, stroke 1.25 — the canon token
 * `--c-ic-sw` wins over the attribute wherever a ladder class is present)
 * under the semantic names the code has always used: `Search` here IS
 * Tabler's IconSearch. `LucideIcon` stays exported as the component type
 * name the codebase knows; it is Tabler's icon type now.
 */

import * as React from 'react';
import {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconApps,
  IconArchive,
  IconArrowBarToDown,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowsExchange,
  IconArrowsMaximize,
  IconArrowsMove,
  IconArrowsSort,
  IconArrowsSplit2,
  IconBallpen,
  IconBan,
  IconBasket,
  IconBinaryTree,
  IconBlockquote,
  IconBolt,
  IconBookmark,
  IconBookmarkPlus,
  IconBooks,
  IconBox,
  IconBraces,
  IconBrain,
  IconBrush,
  IconBulb,
  IconCalendar,
  IconCalendarMonth,
  IconCamera,
  IconChartBar,
  IconChartLine,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircle,
  IconCircleCheck,
  IconCirclePlus,
  IconCircleX,
  IconClick,
  IconClock,
  IconCode,
  IconCommand,
  IconCopy,
  IconCopyCheck,
  IconCopyPlus,
  IconCurrencyDollar,
  IconDatabase,
  IconDeviceDesktop,
  IconDeviceFloppy,
  IconDeviceMobile,
  IconDice5,
  IconDots,
  IconDownload,
  IconDumbbell,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFeather,
  IconFile,
  IconFileCode,
  IconFileImport,
  IconFilePencil,
  IconFilePlus,
  IconFileSearch,
  IconFileText,
  IconFileTypePdf,
  IconFileUnknown,
  IconFileUpload,
  IconFileZip,
  IconFiles,
  IconFilter,
  IconFilterX,
  IconFlask,
  IconFlask2,
  IconFlower,
  IconFolder,
  IconFolderOpen,
  IconFolderPlus,
  IconGhost3,
  IconGitFork,
  IconGripVertical,
  IconHeart,
  IconHelp,
  IconHelpCircle,
  IconHistory,
  IconInfoCircle,
  IconKey,
  IconLayoutGrid,
  IconLayoutSidebar,
  IconLayoutSidebarLeftCollapse,
  IconLink,
  IconLoadBalancer,
  IconLoader2,
  IconLock,
  IconLockOpen,
  IconLogout,
  IconMaximize,
  IconMenu,
  IconMessage,
  IconMessages,
  IconMicrophone,
  IconMicrophoneOff,
  IconMinimize,
  IconMinus,
  IconMoon,
  IconMovie,
  IconMusic,
  IconNews,
  IconPalette,
  IconPaperclip,
  IconPaw,
  IconPencil,
  IconPhoto,
  IconPhotoOff,
  IconPhotoUp,
  IconPill,
  IconPin,
  IconPinnedOff,
  IconPlane,
  IconPlaneDeparture,
  IconPlant,
  IconPlayerPlay,
  IconPlayerStop,
  IconPlayerTrackNext,
  IconPlug,
  IconPlugConnected,
  IconPlus,
  IconQrcode,
  IconReceipt,
  IconRefresh,
  IconReload,
  IconRepeat,
  IconRestore,
  IconRocket,
  IconRotate,
  IconRotateClockwise,
  IconScale,
  IconSchool,
  IconScript,
  IconSearch,
  IconSend,
  IconSettings,
  IconSettings2,
  IconShare3,
  IconShield,
  IconShieldCheck,
  IconShoppingBag,
  IconSignature,
  IconSparkles,
  IconSquare,
  IconStar,
  IconStethoscope,
  IconSun,
  IconTable,
  IconTelescope,
  IconTerminal,
  IconTerminal2,
  IconThumbDown,
  IconThumbUp,
  IconTool,
  IconTrash,
  IconTypography,
  IconUpload,
  IconUser,
  IconUserCheck,
  IconUserX,
  IconUsers,
  IconVariable,
  IconVolume,
  IconVolumeOff,
  IconWand,
  IconWifiOff,
  IconWorld,
  IconWorldSearch,
  IconX,
  IconZoomIn,
  IconZoomOut,
} from '@tabler/icons-react';
import type { IconProps, TablerIcon } from '@tabler/icons-react';

export type LucideIcon = React.ComponentType<IconProps>;

/** The canon's stroke as a default the call site can still override. */
const canon = (Target: TablerIcon, displayName: string): LucideIcon => {
  const C = React.forwardRef<SVGSVGElement, IconProps>((props, ref) =>
    React.createElement(Target, { stroke: 1.25, ref, ...props }),
  );
  C.displayName = displayName;
  return C as unknown as LucideIcon;
};

/* The name is what it means, the target is what Tabler calls it. */
export const AlertCircle: LucideIcon = canon(IconAlertCircle, 'AlertCircle');
export const AlertTriangle: LucideIcon = canon(IconAlertTriangle, 'AlertTriangle');
export const Apps: LucideIcon = canon(IconApps, 'Apps');
export const Archive: LucideIcon = canon(IconArchive, 'Archive');
export const ArchiveRestore: LucideIcon = canon(IconRestore, 'ArchiveRestore');
export const ArrowDown: LucideIcon = canon(IconArrowDown, 'ArrowDown');
export const ArrowDownToLine: LucideIcon = canon(IconArrowBarToDown, 'ArrowDownToLine');
export const ArrowDownUp: LucideIcon = canon(IconArrowsSort, 'ArrowDownUp');
export const ArrowLeft: LucideIcon = canon(IconArrowLeft, 'ArrowLeft');
export const ArrowRight: LucideIcon = canon(IconArrowRight, 'ArrowRight');
export const ArrowRightLeft: LucideIcon = canon(IconArrowsExchange, 'ArrowRightLeft');
export const ArrowUp: LucideIcon = canon(IconArrowUp, 'ArrowUp');
export const ArrowUpDown: LucideIcon = canon(IconArrowsSort, 'ArrowUpDown');
export const Ban: LucideIcon = canon(IconBan, 'Ban');
export const BarChart3: LucideIcon = canon(IconChartBar, 'BarChart3');
export const Beaker: LucideIcon = canon(IconFlask, 'Beaker');
export const BookCopy: LucideIcon = canon(IconBooks, 'BookCopy');
export const Bookmark: LucideIcon = canon(IconBookmark, 'Bookmark');
export const BookmarkPlusIcon: LucideIcon = canon(IconBookmarkPlus, 'BookmarkPlusIcon');
export const Bot: LucideIcon = canon(IconSparkles, 'Bot');
export const Box: LucideIcon = canon(IconBox, 'Box');
export const BoxIcon: LucideIcon = canon(IconBox, 'BoxIcon');
export const Braces: LucideIcon = canon(IconBraces, 'Braces');
export const Brain: LucideIcon = canon(IconBrain, 'Brain');
export const Brush: LucideIcon = canon(IconBrush, 'Brush');
export const Calendar: LucideIcon = canon(IconCalendar, 'Calendar');
export const CalendarDays: LucideIcon = canon(IconCalendarMonth, 'CalendarDays');
export const Camera: LucideIcon = canon(IconCamera, 'Camera');
export const Check: LucideIcon = canon(IconCheck, 'Check');
export const CheckCircle: LucideIcon = canon(IconCircleCheck, 'CheckCircle');
export const CheckCircle2: LucideIcon = canon(IconCircleCheck, 'CheckCircle2');
export const CheckIcon: LucideIcon = canon(IconCheck, 'CheckIcon');
export const ChevronDown: LucideIcon = canon(IconChevronDown, 'ChevronDown');
export const ChevronLeft: LucideIcon = canon(IconChevronLeft, 'ChevronLeft');
export const ChevronRight: LucideIcon = canon(IconChevronRight, 'ChevronRight');
export const ChevronRightIcon: LucideIcon = canon(IconChevronRight, 'ChevronRightIcon');
export const ChevronUp: LucideIcon = canon(IconChevronUp, 'ChevronUp');
export const Circle: LucideIcon = canon(IconCircle, 'Circle');
export const CircleCheckBig: LucideIcon = canon(IconCircleCheck, 'CircleCheckBig');
export const CircleHelpIcon: LucideIcon = canon(IconHelp, 'CircleHelpIcon');
export const CircleIcon: LucideIcon = canon(IconCircle, 'CircleIcon');
export const CircleX: LucideIcon = canon(IconCircleX, 'CircleX');
export const Clock: LucideIcon = canon(IconClock, 'Clock');
export const Clock4: LucideIcon = canon(IconClock, 'Clock4');
export const Code: LucideIcon = canon(IconCode, 'Code');
export const Code2: LucideIcon = canon(IconCode, 'Code2');
export const Cog: LucideIcon = canon(IconSettings2, 'Cog');
export const Command: LucideIcon = canon(IconCommand, 'Command');
export const Copy: LucideIcon = canon(IconCopy, 'Copy');
export const CopyCheck: LucideIcon = canon(IconCopyCheck, 'CopyCheck');
export const CopyPlus: LucideIcon = canon(IconCopyPlus, 'CopyPlus');
export const Database: LucideIcon = canon(IconDatabase, 'Database');
export const Dices: LucideIcon = canon(IconDice5, 'Dices');
export const DollarSign: LucideIcon = canon(IconCurrencyDollar, 'DollarSign');
export const Download: LucideIcon = canon(IconDownload, 'Download');
export const Dumbbell: LucideIcon = canon(IconDumbbell, 'Dumbbell');
export const EarthIcon: LucideIcon = canon(IconWorld, 'EarthIcon');
export const Edit3: LucideIcon = canon(IconSignature, 'Edit3');
export const EditIcon: LucideIcon = canon(IconEdit, 'EditIcon');
export const Ellipsis: LucideIcon = canon(IconDots, 'Ellipsis');
export const Expand: LucideIcon = canon(IconArrowsMaximize, 'Expand');
export const ExternalLink: LucideIcon = canon(IconExternalLink, 'ExternalLink');
export const Eye: LucideIcon = canon(IconEye, 'Eye');
export const EyeOff: LucideIcon = canon(IconEyeOff, 'EyeOff');
export const Feather: LucideIcon = canon(IconFeather, 'Feather');
export const File: LucideIcon = canon(IconFile, 'File');
export const FileArchive: LucideIcon = canon(IconFileZip, 'FileArchive');
export const FileCode: LucideIcon = canon(IconFileCode, 'FileCode');
export const FileImage: LucideIcon = canon(IconPhoto, 'FileImage');
export const FileImageIcon: LucideIcon = canon(IconPhoto, 'FileImageIcon');
export const FilePenLine: LucideIcon = canon(IconFilePencil, 'FilePenLine');
export const FilePlus: LucideIcon = canon(IconFilePlus, 'FilePlus');
export const FilePlus2: LucideIcon = canon(IconFilePlus, 'FilePlus2');
export const FileQuestion: LucideIcon = canon(IconFileUnknown, 'FileQuestion');
export const FileSearch: LucideIcon = canon(IconFileSearch, 'FileSearch');
export const FileSearchIcon: LucideIcon = canon(IconFileSearch, 'FileSearchIcon');
export const FileSpreadsheet: LucideIcon = canon(IconTable, 'FileSpreadsheet');
export const FileText: LucideIcon = canon(IconFileText, 'FileText');
export const FileType2Icon: LucideIcon = canon(IconFileText, 'FileType2Icon');
export const FileTypePdf: LucideIcon = canon(IconFileTypePdf, 'FileTypePdf');
export const FileUp: LucideIcon = canon(IconFileUpload, 'FileUp');
export const Files: LucideIcon = canon(IconFiles, 'Files');
export const Film: LucideIcon = canon(IconMovie, 'Film');
export const FilterX: LucideIcon = canon(IconFilterX, 'FilterX');
export const FlaskConical: LucideIcon = canon(IconFlask2, 'FlaskConical');
export const Flower2: LucideIcon = canon(IconFlower, 'Flower2');
export const Folder: LucideIcon = canon(IconFolder, 'Folder');
export const FolderOpen: LucideIcon = canon(IconFolderOpen, 'FolderOpen');
export const FolderPlus: LucideIcon = canon(IconFolderPlus, 'FolderPlus');
export const GitFork: LucideIcon = canon(IconGitFork, 'GitFork');
export const Globe: LucideIcon = canon(IconWorld, 'Globe');
export const GraduationCap: LucideIcon = canon(IconSchool, 'GraduationCap');
export const GraduationCapIcon: LucideIcon = canon(IconSchool, 'GraduationCapIcon');
export const GripVertical: LucideIcon = canon(IconGripVertical, 'GripVertical');
export const Heart: LucideIcon = canon(IconHeart, 'Heart');
export const HelpCircle: LucideIcon = canon(IconHelpCircle, 'HelpCircle');
export const History: LucideIcon = canon(IconHistory, 'History');
export const Image: LucideIcon = canon(IconPhoto, 'Image');
export const ImageIcon: LucideIcon = canon(IconPhoto, 'ImageIcon');
export const ImageOff: LucideIcon = canon(IconPhotoOff, 'ImageOff');
export const ImageUpIcon: LucideIcon = canon(IconPhotoUp, 'ImageUpIcon');
export const Import: LucideIcon = canon(IconFileImport, 'Import');
export const Info: LucideIcon = canon(IconInfoCircle, 'Info');
export const InfoIcon: LucideIcon = canon(IconInfoCircle, 'InfoIcon');
export const Key: LucideIcon = canon(IconKey, 'Key');
export const KeyRound: LucideIcon = canon(IconKey, 'KeyRound');
export const KeyRoundIcon: LucideIcon = canon(IconKey, 'KeyRoundIcon');
export const LayoutGrid: LucideIcon = canon(IconLayoutGrid, 'LayoutGrid');
export const Lightbulb: LucideIcon = canon(IconBulb, 'Lightbulb');
export const LightbulbIcon: LucideIcon = canon(IconBulb, 'LightbulbIcon');
export const LineChartIcon: LucideIcon = canon(IconChartLine, 'LineChartIcon');
export const Link: LucideIcon = canon(IconLink, 'Link');
export const Link2: LucideIcon = canon(IconLink, 'Link2');
export const ListFilter: LucideIcon = canon(IconFilter, 'ListFilter');
export const LoadBalancer: LucideIcon = canon(IconLoadBalancer, 'LoadBalancer');
export const Loader2: LucideIcon = canon(IconLoader2, 'Loader2');
export const LockIcon: LucideIcon = canon(IconLock, 'LockIcon');
export const LogOut: LucideIcon = canon(IconLogout, 'LogOut');
export const Maximize2: LucideIcon = canon(IconMaximize, 'Maximize2');
export const Menu: LucideIcon = canon(IconMenu, 'Menu');
export const MessageCircleDashed: LucideIcon = canon(IconGhost3, 'MessageCircleDashed');
export const MessageSquare: LucideIcon = canon(IconMessage, 'MessageSquare');
export const MessagesSquare: LucideIcon = canon(IconMessages, 'MessagesSquare');
export const Mic: LucideIcon = canon(IconMicrophone, 'Mic');
export const MicOff: LucideIcon = canon(IconMicrophoneOff, 'MicOff');
export const Minimize2: LucideIcon = canon(IconMinimize, 'Minimize2');
export const Minus: LucideIcon = canon(IconMinus, 'Minus');
export const Monitor: LucideIcon = canon(IconDeviceDesktop, 'Monitor');
export const Moon: LucideIcon = canon(IconMoon, 'Moon');
export const MoreHorizontal: LucideIcon = canon(IconDots, 'MoreHorizontal');
export const MousePointerClick: LucideIcon = canon(IconClick, 'MousePointerClick');
export const Move: LucideIcon = canon(IconArrowsMove, 'Move');
export const Music: LucideIcon = canon(IconMusic, 'Music');
export const Newspaper: LucideIcon = canon(IconNews, 'Newspaper');
export const NotebookPen: LucideIcon = canon(IconBlockquote, 'NotebookPen');
export const Palette: LucideIcon = canon(IconPalette, 'Palette');
export const PanelLeftClose: LucideIcon = canon(IconLayoutSidebarLeftCollapse, 'PanelLeftClose');
export const PanelLeftOpen: LucideIcon = canon(IconLayoutSidebar, 'PanelLeftOpen');
export const Paperclip: LucideIcon = canon(IconPaperclip, 'Paperclip');
export const PawPrint: LucideIcon = canon(IconPaw, 'PawPrint');
export const Pen: LucideIcon = canon(IconBallpen, 'Pen');
export const PenLine: LucideIcon = canon(IconSignature, 'PenLine');
export const PenLineIcon: LucideIcon = canon(IconSignature, 'PenLineIcon');
export const PenTool: LucideIcon = canon(IconBrush, 'PenTool');
export const Pencil: LucideIcon = canon(IconPencil, 'Pencil');
export const Pill: LucideIcon = canon(IconPill, 'Pill');
export const Pin: LucideIcon = canon(IconPin, 'Pin');
export const PinOff: LucideIcon = canon(IconPinnedOff, 'PinOff');
export const Plane: LucideIcon = canon(IconPlane, 'Plane');
export const PlaneTakeoffIcon: LucideIcon = canon(IconPlaneDeparture, 'PlaneTakeoffIcon');
export const Play: LucideIcon = canon(IconPlayerPlay, 'Play');
export const PlayerStop: LucideIcon = canon(IconPlayerStop, 'PlayerStop');
export const PlayerTrackNext: LucideIcon = canon(IconPlayerTrackNext, 'PlayerTrackNext');
export const Plug: LucideIcon = canon(IconPlug, 'Plug');
export const PlugZap: LucideIcon = canon(IconPlugConnected, 'PlugZap');
export const Plus: LucideIcon = canon(IconPlus, 'Plus');
export const PlusCircle: LucideIcon = canon(IconCirclePlus, 'PlusCircle');
export const PlusCircleIcon: LucideIcon = canon(IconCirclePlus, 'PlusCircleIcon');
export const Popcorn: LucideIcon = canon(IconMovie, 'Popcorn');
export const QrCode: LucideIcon = canon(IconQrcode, 'QrCode');
export const Receipt: LucideIcon = canon(IconReceipt, 'Receipt');
export const RefreshCcw: LucideIcon = canon(IconRotate, 'RefreshCcw');
export const RefreshCw: LucideIcon = canon(IconRefresh, 'RefreshCw');
export const Reload: LucideIcon = canon(IconReload, 'Reload');
export const Repeat: LucideIcon = canon(IconRepeat, 'Repeat');
export const Rocket: LucideIcon = canon(IconRocket, 'Rocket');
export const RotateCcw: LucideIcon = canon(IconRotate, 'RotateCcw');
export const RotateCw: LucideIcon = canon(IconRotateClockwise, 'RotateCw');
export const Save: LucideIcon = canon(IconDeviceFloppy, 'Save');
export const Scale: LucideIcon = canon(IconScale, 'Scale');
export const ScrollText: LucideIcon = canon(IconScript, 'ScrollText');
export const Search: LucideIcon = canon(IconSearch, 'Search');
export const Send: LucideIcon = canon(IconSend, 'Send');
export const Settings: LucideIcon = canon(IconSettings, 'Settings');
export const Settings2: LucideIcon = canon(IconApps, 'Settings2');
export const SettingsIcon: LucideIcon = canon(IconSettings, 'SettingsIcon');
export const Share2: LucideIcon = canon(IconShare3, 'Share2');
export const Share2Icon: LucideIcon = canon(IconShare3, 'Share2Icon');
export const Shield: LucideIcon = canon(IconShield, 'Shield');
export const ShieldEllipsis: LucideIcon = canon(IconShieldCheck, 'ShieldEllipsis');
export const ShoppingBag: LucideIcon = canon(IconShoppingBag, 'ShoppingBag');
export const ShoppingBagIcon: LucideIcon = canon(IconShoppingBag, 'ShoppingBagIcon');
export const ShoppingBasket: LucideIcon = canon(IconBasket, 'ShoppingBasket');
export const SlidersHorizontal: LucideIcon = canon(IconAdjustmentsHorizontal, 'SlidersHorizontal');
export const Smartphone: LucideIcon = canon(IconDeviceMobile, 'Smartphone');
export const SmartphoneIcon: LucideIcon = canon(IconDeviceMobile, 'SmartphoneIcon');
export const Sparkles: LucideIcon = canon(IconSparkles, 'Sparkles');
export const Split: LucideIcon = canon(IconArrowsSplit2, 'Split');
export const Sprout: LucideIcon = canon(IconPlant, 'Sprout');
export const Square: LucideIcon = canon(IconSquare, 'Square');
export const SquarePen: LucideIcon = canon(IconEdit, 'SquarePen');
export const SquareTerminal: LucideIcon = canon(IconTerminal2, 'SquareTerminal');
export const Star: LucideIcon = canon(IconStar, 'Star');
export const Stethoscope: LucideIcon = canon(IconStethoscope, 'Stethoscope');
export const Sun: LucideIcon = canon(IconSun, 'Sun');
export const TableIcon: LucideIcon = canon(IconTable, 'TableIcon');
export const Telescope: LucideIcon = canon(IconTelescope, 'Telescope');
export const Terminal: LucideIcon = canon(IconTerminal, 'Terminal');
export const TerminalSquareIcon: LucideIcon = canon(IconCode, 'TerminalSquareIcon');
export const ThumbsDown: LucideIcon = canon(IconThumbDown, 'ThumbsDown');
export const ThumbsUp: LucideIcon = canon(IconThumbUp, 'ThumbsUp');
export const Trash: LucideIcon = canon(IconTrash, 'Trash');
export const Trash2: LucideIcon = canon(IconTrash, 'Trash2');
export const TrashIcon: LucideIcon = canon(IconTrash, 'TrashIcon');
export const TriangleAlert: LucideIcon = canon(IconAlertTriangle, 'TriangleAlert');
export const Type: LucideIcon = canon(IconTypography, 'Type');
export const UnlockIcon: LucideIcon = canon(IconLockOpen, 'UnlockIcon');
export const Upload: LucideIcon = canon(IconUpload, 'Upload');
export const User: LucideIcon = canon(IconUser, 'User');
export const UserCheck: LucideIcon = canon(IconUserCheck, 'UserCheck');
export const UserX: LucideIcon = canon(IconUserX, 'UserX');
export const Users: LucideIcon = canon(IconUsers, 'Users');
export const Variable: LucideIcon = canon(IconVariable, 'Variable');
export const Volume2: LucideIcon = canon(IconVolume, 'Volume2');
export const VolumeOff: LucideIcon = canon(IconVolumeOff, 'VolumeOff');
export const WandSparkles: LucideIcon = canon(IconWand, 'WandSparkles');
export const Waypoints: LucideIcon = canon(IconBinaryTree, 'Waypoints');
export const WifiOff: LucideIcon = canon(IconWifiOff, 'WifiOff');
export const WorldSearch: LucideIcon = canon(IconWorldSearch, 'WorldSearch');
export const Wrench: LucideIcon = canon(IconTool, 'Wrench');
export const X: LucideIcon = canon(IconX, 'X');
export const XCircle: LucideIcon = canon(IconCircleX, 'XCircle');
export const XIcon: LucideIcon = canon(IconX, 'XIcon');
export const Zap: LucideIcon = canon(IconBolt, 'Zap');
export const ZoomIn: LucideIcon = canon(IconZoomIn, 'ZoomIn');
export const ZoomOut: LucideIcon = canon(IconZoomOut, 'ZoomOut');

/* ---- not in Tabler's catalog: geometry kept inline until redrawn ---- */

type SvgProps = React.SVGProps<SVGSVGElement> & { size?: number | string };

const custom = (paths: string, displayName: string): LucideIcon => {
  const C = React.forwardRef<SVGSVGElement, SvgProps>(({ size = '1em', ...props }, ref) =>
    React.createElement('svg', {
      ref,
      xmlns: 'http://www.w3.org/2000/svg',
      width: size,
      height: size,
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: 1.25,
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
      ...props,
      dangerouslySetInnerHTML: { __html: paths },
    }),
  );
  C.displayName = displayName;
  return C as unknown as LucideIcon;
};

export const MessageSquareDashed: LucideIcon = custom(
  '<path d="M14 3h2" /><path d="M16 19h-2" /><path d="M2 12v-2" /><path d="M2 16v5.286a.71.71 0 0 0 1.212.502l1.149-1.149" /><path d="M20 19a2 2 0 0 0 2-2v-1" /><path d="M22 10v2" /><path d="M22 6V5a2 2 0 0 0-2-2" /><path d="M4 3a2 2 0 0 0-2 2v1" /><path d="M8 19h2" /><path d="M8 3h2" />',
  'MessageSquareDashed',
);
export const SquareSlash: LucideIcon = custom(
  '<rect width="18" height="18" x="3" y="3" rx="2" /><line x1="9" x2="15" y1="15" y2="9" />',
  'SquareSlash',
);
