/**
 * GENERATED by scripts/gen-icon-shims.mjs from scripts/icons.map.json — edit
 * the map, not this file.
 *
 * The app's icons are Phosphor (weight Regular; pass weight="fill" for active
 * states) under the semantic names the code has always used: `Search` here
 * IS Phosphor's MagnifyingGlass. `LucideIcon` stays exported as the component
 * type name the codebase knows; it is Phosphor's Icon type now.
 */

import * as React from 'react';
import type { Icon } from '@phosphor-icons/react';

export type LucideIcon = Icon;

/* Same subject, same name in both sets. */
export {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Brain,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  Circle,
  Clock,
  Code,
  Command,
  Copy,
  Database,
  Eye,
  Feather,
  File,
  FileCode,
  FileImage,
  FilePlus,
  FileText,
  Files,
  Folder,
  FolderPlus,
  GitFork,
  Globe,
  GraduationCap,
  Heart,
  Image,
  Info,
  Key,
  Lightbulb,
  Link,
  Minus,
  Monitor,
  Moon,
  Newspaper,
  Palette,
  Paperclip,
  PawPrint,
  Pen,
  Pencil,
  Pill,
  Play,
  Plus,
  PlusCircle,
  Popcorn,
  QrCode,
  Receipt,
  Rocket,
  Shield,
  ShoppingBag,
  SlidersHorizontal,
  Square,
  Star,
  Stethoscope,
  Sun,
  Terminal,
  Trash,
  User,
  UserCheck,
  Users,
  Wrench,
  X,
  XCircle,
} from '@phosphor-icons/react';

/* Renames: the name is what it means, the target is what Phosphor calls it. */
export { WarningCircle as AlertCircle } from '@phosphor-icons/react';
export { Warning as AlertTriangle } from '@phosphor-icons/react';
export { BoxArrowUp as ArchiveRestore } from '@phosphor-icons/react';
export { ArrowLineDown as ArrowDownToLine } from '@phosphor-icons/react';
export { ArrowsDownUp as ArrowDownUp } from '@phosphor-icons/react';
export { ArrowsLeftRight as ArrowRightLeft } from '@phosphor-icons/react';
export { ArrowsDownUp as ArrowUpDown } from '@phosphor-icons/react';
export { Prohibit as Ban } from '@phosphor-icons/react';
export { ChartBar as BarChart3 } from '@phosphor-icons/react';
export { Flask as Beaker } from '@phosphor-icons/react';
export { Books as BookCopy } from '@phosphor-icons/react';
export { BookmarkSimple as Bookmark } from '@phosphor-icons/react';
export { Bookmarks as BookmarkPlusIcon } from '@phosphor-icons/react';
export { Cube as Box } from '@phosphor-icons/react';
export { Cube as BoxIcon } from '@phosphor-icons/react';
export { BracketsCurly as Braces } from '@phosphor-icons/react';
export { PaintBrush as Brush } from '@phosphor-icons/react';
export { CalendarDots as CalendarDays } from '@phosphor-icons/react';
export { CheckCircle as CheckCircle2 } from '@phosphor-icons/react';
export { Check as CheckIcon } from '@phosphor-icons/react';
export { CaretDown as ChevronDown } from '@phosphor-icons/react';
export { CaretLeft as ChevronLeft } from '@phosphor-icons/react';
export { CaretRight as ChevronRight } from '@phosphor-icons/react';
export { CaretRight as ChevronRightIcon } from '@phosphor-icons/react';
export { CaretUp as ChevronUp } from '@phosphor-icons/react';
export { CheckCircle as CircleCheckBig } from '@phosphor-icons/react';
export { Question as CircleHelpIcon } from '@phosphor-icons/react';
export { Circle as CircleIcon } from '@phosphor-icons/react';
export { XCircle as CircleX } from '@phosphor-icons/react';
export { Clock as Clock4 } from '@phosphor-icons/react';
export { CodeSimple as Code2 } from '@phosphor-icons/react';
export { Gear as Cog } from '@phosphor-icons/react';
export { CheckSquare as CopyCheck } from '@phosphor-icons/react';
export { CopySimple as CopyPlus } from '@phosphor-icons/react';
export { DiceFive as Dices } from '@phosphor-icons/react';
export { CurrencyDollar as DollarSign } from '@phosphor-icons/react';
export { DownloadSimple as Download } from '@phosphor-icons/react';
export { Barbell as Dumbbell } from '@phosphor-icons/react';
export { GlobeHemisphereWest as EarthIcon } from '@phosphor-icons/react';
export { PencilLine as Edit3 } from '@phosphor-icons/react';
export { NotePencil as EditIcon } from '@phosphor-icons/react';
export { DotsThree as Ellipsis } from '@phosphor-icons/react';
export { ArrowsOut as Expand } from '@phosphor-icons/react';
export { ArrowSquareOut as ExternalLink } from '@phosphor-icons/react';
export { EyeSlash as EyeOff } from '@phosphor-icons/react';
export { FileImage as FileImageIcon } from '@phosphor-icons/react';
export { NotePencil as FilePenLine } from '@phosphor-icons/react';
export { FilePlus as FilePlus2 } from '@phosphor-icons/react';
export { FileDashed as FileQuestion } from '@phosphor-icons/react';
export { FileMagnifyingGlass as FileSearch } from '@phosphor-icons/react';
export { FileXls as FileSpreadsheet } from '@phosphor-icons/react';
export { FileText as FileType2Icon } from '@phosphor-icons/react';
export { FileArrowUp as FileUp } from '@phosphor-icons/react';
export { FunnelX as FilterX } from '@phosphor-icons/react';
export { Flask as FlaskConical } from '@phosphor-icons/react';
export { Flower as Flower2 } from '@phosphor-icons/react';
export { GraduationCap as GraduationCapIcon } from '@phosphor-icons/react';
export { DotsSixVertical as GripVertical } from '@phosphor-icons/react';
export { Question as HelpCircle } from '@phosphor-icons/react';
export { ClockCounterClockwise as History } from '@phosphor-icons/react';
export { Image as ImageIcon } from '@phosphor-icons/react';
export { ImageBroken as ImageOff } from '@phosphor-icons/react';
export { ImageSquare as ImageUpIcon } from '@phosphor-icons/react';
export { TrayArrowDown as Import } from '@phosphor-icons/react';
export { Info as InfoIcon } from '@phosphor-icons/react';
export { Key as KeyRound } from '@phosphor-icons/react';
export { Key as KeyRoundIcon } from '@phosphor-icons/react';
export { SquaresFour as LayoutGrid } from '@phosphor-icons/react';
export { Lightbulb as LightbulbIcon } from '@phosphor-icons/react';
export { ChartLine as LineChartIcon } from '@phosphor-icons/react';
export { LinkSimple as Link2 } from '@phosphor-icons/react';
export { FunnelSimple as ListFilter } from '@phosphor-icons/react';
export { CircleNotch as Loader2 } from '@phosphor-icons/react';
export { Lock as LockIcon } from '@phosphor-icons/react';
export { SignOut as LogOut } from '@phosphor-icons/react';
export { ArrowsOutSimple as Maximize2 } from '@phosphor-icons/react';
export { List as Menu } from '@phosphor-icons/react';
export { ClockCountdown as MessageCircleDashed } from '@phosphor-icons/react';
export { Chat as MessageSquare } from '@phosphor-icons/react';
export { Chats as MessagesSquare } from '@phosphor-icons/react';
export { MicrophoneSlash as MicOff } from '@phosphor-icons/react';
export { ArrowsInSimple as Minimize2 } from '@phosphor-icons/react';
export { DotsThree as MoreHorizontal } from '@phosphor-icons/react';
export { CursorClick as MousePointerClick } from '@phosphor-icons/react';
export { ArrowsOutCardinal as Move } from '@phosphor-icons/react';
export { MusicNotes as Music } from '@phosphor-icons/react';
export { NotePencil as NotebookPen } from '@phosphor-icons/react';
export { CaretLineLeft as PanelLeftClose } from '@phosphor-icons/react';
export { SidebarSimple as PanelLeftOpen } from '@phosphor-icons/react';
export { PencilLine as PenLine } from '@phosphor-icons/react';
export { PencilLine as PenLineIcon } from '@phosphor-icons/react';
export { PenNib as PenTool } from '@phosphor-icons/react';
export { PushPin as Pin } from '@phosphor-icons/react';
export { PushPinSlash as PinOff } from '@phosphor-icons/react';
export { Airplane as Plane } from '@phosphor-icons/react';
export { AirplaneTakeoff as PlaneTakeoffIcon } from '@phosphor-icons/react';
export { PlugCharging as PlugZap } from '@phosphor-icons/react';
export { PlusCircle as PlusCircleIcon } from '@phosphor-icons/react';
export { ArrowsCounterClockwise as RefreshCcw } from '@phosphor-icons/react';
export { ArrowsClockwise as RefreshCw } from '@phosphor-icons/react';
export { ArrowCounterClockwise as RotateCcw } from '@phosphor-icons/react';
export { ArrowClockwise as RotateCw } from '@phosphor-icons/react';
export { FloppyDisk as Save } from '@phosphor-icons/react';
export { Scales as Scale } from '@phosphor-icons/react';
export { Scroll as ScrollText } from '@phosphor-icons/react';
export { MagnifyingGlass as Search } from '@phosphor-icons/react';
export { PaperPlaneTilt as Send } from '@phosphor-icons/react';
export { Gear as Settings } from '@phosphor-icons/react';
export { SlidersHorizontal as Settings2 } from '@phosphor-icons/react';
export { Gear as SettingsIcon } from '@phosphor-icons/react';
export { ShareNetwork as Share2 } from '@phosphor-icons/react';
export { ShareNetwork as Share2Icon } from '@phosphor-icons/react';
export { ShieldCheck as ShieldEllipsis } from '@phosphor-icons/react';
export { ShoppingBag as ShoppingBagIcon } from '@phosphor-icons/react';
export { Basket as ShoppingBasket } from '@phosphor-icons/react';
export { DeviceMobile as Smartphone } from '@phosphor-icons/react';
export { DeviceMobile as SmartphoneIcon } from '@phosphor-icons/react';
export { Sparkle as Sparkles } from '@phosphor-icons/react';
export { Plant as Sprout } from '@phosphor-icons/react';
export { NotePencil as SquarePen } from '@phosphor-icons/react';
export { TerminalWindow as SquareTerminal } from '@phosphor-icons/react';
export { Binoculars as Telescope } from '@phosphor-icons/react';
export { TerminalWindow as TerminalSquareIcon } from '@phosphor-icons/react';
export { Trash as Trash2 } from '@phosphor-icons/react';
export { Trash as TrashIcon } from '@phosphor-icons/react';
export { Warning as TriangleAlert } from '@phosphor-icons/react';
export { TextT as Type } from '@phosphor-icons/react';
export { LockOpen as UnlockIcon } from '@phosphor-icons/react';
export { UploadSimple as Upload } from '@phosphor-icons/react';
export { UserMinus as UserX } from '@phosphor-icons/react';
export { Function as Variable } from '@phosphor-icons/react';
export { MagicWand as WandSparkles } from '@phosphor-icons/react';
export { TreeStructure as Waypoints } from '@phosphor-icons/react';
export { WifiSlash as WifiOff } from '@phosphor-icons/react';
export { X as XIcon } from '@phosphor-icons/react';
export { Lightning as Zap } from '@phosphor-icons/react';
export { MagnifyingGlassPlus as ZoomIn } from '@phosphor-icons/react';
export { MagnifyingGlassMinus as ZoomOut } from '@phosphor-icons/react';

/* ---- not in Phosphor's catalog: lucide geometry inline until redrawn ---- */

type SvgProps = React.SVGProps<SVGSVGElement> & { size?: number | string };

const custom = (paths: string, displayName: string): LucideIcon => {
  const C = React.forwardRef<SVGSVGElement, SvgProps>(({ size = '1em', ...props }, ref) =>
    React.createElement('svg', {
      ref,
      xmlns: 'http://www.w3.org/2000/svg',
      width: size,
      height: size,
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: 2,
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
      ...props,
      dangerouslySetInnerHTML: { __html: paths },
    }),
  );
  C.displayName = displayName;
  return C as unknown as LucideIcon;
};

export const Bot: LucideIcon = custom(
  '<path d="M12 8V4H8" /><rect width="16" height="12" x="4" y="8" rx="2" /><path d="M2 14h2" /><path d="M20 14h2" /><path d="M15 13v2" /><path d="M9 13v2" />',
  'Bot',
);
export const MessageSquareDashed: LucideIcon = custom(
  '<path d="M14 3h2" /><path d="M16 19h-2" /><path d="M2 12v-2" /><path d="M2 16v5.286a.71.71 0 0 0 1.212.502l1.149-1.149" /><path d="M20 19a2 2 0 0 0 2-2v-1" /><path d="M22 10v2" /><path d="M22 6V5a2 2 0 0 0-2-2" /><path d="M4 3a2 2 0 0 0-2 2v1" /><path d="M8 19h2" /><path d="M8 3h2" />',
  'MessageSquareDashed',
);
export const SquareSlash: LucideIcon = custom(
  '<rect width="18" height="18" x="3" y="3" rx="2" /><line x1="9" x2="15" y1="15" y2="9" />',
  'SquareSlash',
);
